import type { Partner } from "@/features/launch-app/types";

export const BENEFIT_CATEGORIES = ["All", "General", "Wealth & Finance", "Lifestyle & Retail", "Exclusive Privileges", "Hidden Gems"];

export const PARTNERS_DATA: Partner[] = [
  {
    id: "alpha",
    name: "Partner Alpha",
    status: "ELIGIBLE",
    eligible: true,
    delay: "0.4s",
    campaigns: [
      {
        name: "Yield Booster",
        type: "Yield Boost",
        chains: ["ETH", "Base"],
        category: "Wealth & Finance",
        period: "Jan 30 – Mar 1, 2026",
        eligible: true,
        desc: "Prestige rewards for verified value. We've matched your Platinum profile with this exclusive Yield Booster. Secure your spot with a single click.",
        tags: [
          { persona: "Smart Saver", type: "verified" },
          { persona: "Profit Hunter", type: "verified" },
          { tier: "Platinum+", type: "tier" },
        ],
      },
      {
        name: "ICO Allocation",
        type: "Early Access",
        chains: ["ETH"],
        category: "Exclusive Privileges",
        period: "Jan 30 – Mar 1, 2026",
        eligible: false,
        desc: "Exclusive allocation round for Black-tier members.",
        tags: [
          { persona: "Strategic Holder", type: "requires" },
          { tier: "Black", type: "tier" },
        ],
        qualifySteps: [
          "Achieve the Strategic Holder persona by maintaining core assets long-term",
          "Reach the Black membership tier",
          "Maintain tier status for at least 7 consecutive days",
        ],
      },
    ],
  },
  {
    id: "beta",
    name: "Partner Beta",
    status: "REACH TO UNLOCK",
    eligible: false,
    delay: "0.5s",
    campaigns: [
      {
        name: "Premium Lending Drop",
        type: "Cashback",
        chains: ["ETH", "BSC", "Base"],
        category: "Wealth & Finance",
        period: "Feb 15 – Apr 30, 2026",
        eligible: false,
        desc: "This campaign requires the Wealth Guard persona. Maintain significant stable reserves to qualify.",
        tags: [
          { persona: "Wealth Guard", type: "requires" },
          { persona: "Cash Manager", type: "requires" },
          { tier: "Gold+", type: "tier" },
        ],
        qualifySteps: [
          "Maintain $50,000+ in stable reserves across supported chains",
          "Hold stablecoins for 30+ consecutive days",
          "Reach Gold tier or above on your Gravii ID",
        ],
      },
    ],
  },
  {
    id: "gamma",
    name: "Partner Gamma",
    status: "COMING SOON",
    eligible: null,
    delay: "0.55s",
    campaigns: [
      {
        name: "Lifestyle Rewards",
        type: "Loyalty Reward",
        chains: ["All"],
        category: "Lifestyle & Retail",
        period: "Opens Mar 15, 2026",
        eligible: null,
        desc: "Details will be revealed when the campaign goes live. Stay tuned.",
        tags: [{ tier: "All Tiers", type: "open" }],
      },
    ],
  },
  {
    id: "delta",
    name: "Partner Delta",
    status: "INVITE ONLY",
    eligible: false,
    delay: "0.6s",
    campaigns: [
      {
        name: "Collector's Access",
        type: "Early Access",
        chains: ["ETH"],
        category: "Exclusive Privileges",
        period: "Ongoing",
        eligible: false,
        desc: "This privilege is reserved for users with the NFT Collector persona. Invitations are issued based on on-chain collection activity.",
        tags: [
          { persona: "NFT Collector", type: "targeting" },
          { tier: "Gold+", type: "tier" },
        ],
        qualifySteps: [
          "Build the NFT Collector persona by trading and collecting NFTs at scale",
          "Reach Gold tier or above",
          "Maintain active collection activity for 14+ days",
        ],
      },
      {
        name: "Collector's Circle",
        type: "Loyalty Reward",
        chains: ["ETH", "Base"],
        category: "Exclusive Privileges",
        period: "Ongoing",
        eligible: false,
        desc: "Inner circle access for top-tier collectors.",
        tags: [
          { persona: "NFT Collector", type: "targeting" },
          { persona: "Power User", type: "targeting" },
          { tier: "Platinum+", type: "tier" },
        ],
        qualifySteps: [
          "Achieve both NFT Collector and Power User personas",
          "Reach Platinum tier or above",
          "Be in the top 1,000 collectors on Standing",
        ],
      },
      {
        name: "Early Mint Pass",
        type: "Airdrop",
        chains: ["ETH", "Base"],
        category: "Hidden Gems",
        period: "Apr 1 – Apr 30, 2026",
        eligible: false,
        desc: "Priority minting access for upcoming partner drops.",
        tags: [
          { persona: "NFT Collector", type: "verified" },
          { tier: "All Tiers", type: "open" },
        ],
        qualifySteps: ["Achieve the NFT Collector persona", "Any membership tier qualifies"],
      },
    ],
  },
  {
    id: "epsilon",
    name: "Partner Epsilon",
    status: "ELIGIBLE",
    eligible: true,
    delay: "0.65s",
    campaigns: [
      {
        name: "Trading Fee Rebate",
        type: "Fee Discount",
        chains: ["ETH", "BSC", "ARB"],
        category: "Wealth & Finance",
        period: "Feb 1 – May 31, 2026",
        eligible: true,
        desc: "Earn back a percentage of your trading fees based on your monthly volume. Verified Active Traders get priority access.",
        tags: [
          { persona: "Active Trader", type: "verified" },
          { persona: "Swing Trader", type: "verified" },
          { tier: "Classic+", type: "tier" },
        ],
      },
      {
        name: "VIP Desk Access",
        type: "Early Access",
        chains: ["All"],
        category: "Exclusive Privileges",
        period: "Ongoing",
        eligible: true,
        desc: "Direct access to a dedicated trading desk with premium execution and priority support.",
        tags: [
          { persona: "Active Trader", type: "verified" },
          { tier: "Platinum+", type: "tier" },
        ],
      },
    ],
  },
  {
    id: "zeta",
    name: "Partner Zeta",
    status: "ELIGIBLE",
    eligible: true,
    delay: "0.7s",
    campaigns: [
      {
        name: "Community Airdrop",
        type: "Airdrop",
        chains: ["All"],
        category: "General",
        period: "Mar 1 – Mar 31, 2026",
        eligible: true,
        desc: "A surprise token distribution for all active Gravii members. No strings attached — just show up.",
        tags: [{ tier: "All Tiers", type: "open" }],
      },
    ],
  },
  {
    id: "eta",
    name: "Partner Eta",
    status: "REACH TO UNLOCK",
    eligible: false,
    delay: "0.75s",
    campaigns: [
      {
        name: "Private Round Access",
        type: "Early Access",
        chains: ["ETH"],
        category: "Wealth & Finance",
        period: "Apr 1 – Jun 30, 2026",
        eligible: false,
        desc: "Early-stage investment allocation reserved for Major Investor persona holders with significant on-chain capital commitment.",
        tags: [
          { persona: "Major Investor", type: "requires" },
          { persona: "Wealth Guard", type: "requires" },
          { tier: "Black", type: "tier" },
        ],
        qualifySteps: [
          "Commit significant capital to high-cap assets to build market trust",
          "Maintain Wealth Guard-level stable reserves",
          "Achieve Black membership tier",
        ],
      },
      {
        name: "Luxury Travel Package",
        type: "Loyalty Reward",
        chains: ["All"],
        category: "Lifestyle & Retail",
        period: "May 1 – Jul 31, 2026",
        eligible: false,
        desc: "Exclusive travel packages and premium hospitality experiences for top-tier members.",
        tags: [
          { persona: "Major Investor", type: "requires" },
          { tier: "Platinum+", type: "tier" },
        ],
        qualifySteps: [
          "Achieve the Major Investor persona",
          "Reach Platinum tier or above",
          "Maintain tier for at least 14 days",
        ],
      },
    ],
  },
  {
    id: "theta",
    name: "Partner Theta",
    status: "INELIGIBLE",
    eligible: "ineligible",
    delay: "0.8s",
    campaigns: [
      {
        name: "Growth Accelerator",
        type: "Referral Bonus",
        chains: ["ETH", "Base", "ARB"],
        category: "Hidden Gems",
        period: "Apr 15 – May 31, 2026",
        eligible: "ineligible",
        desc: "This campaign is strictly limited to users who meet the exact persona and tier requirements. No alternative path to entry.",
        tags: [
          { persona: "Rising Star", type: "targeting" },
          { persona: "New Voyager", type: "targeting" },
          { tier: "Classic+", type: "tier" },
        ],
      },
    ],
  },
];
