import type { PanelConfig } from "@/features/launch-app/types";

export const PANELS: PanelConfig[] = [
  {
    id: "profile",
    num: "01",
    tab: "GRAVII ID",
    sub: "GRAVII ID",
    editorCopy: "Your identity, distilled.",
    dark: false,
    bg: "#F5F2EB",
    bgHover: "#EDEAE3",
  },
  {
    id: "lookup",
    num: "02",
    tab: "X-RAY",
    sub: "VERIFY",
    editorCopy: "Peel back any account.",
    dark: false,
    bg: "#F0EDE6",
    bgHover: "#F0EDE6",
    xray: true,
  },
  {
    id: "leaderboard",
    num: "03",
    tab: "STANDING",
    sub: "COMING SOON",
    editorCopy: "Rankings, soon.",
    dark: false,
    bg: "#EDEAE3",
    bgHover: "#1A1A1A",
    hoverDark: true,
  },
  {
    id: "discovery",
    num: "04",
    tab: "DISCOVERY",
    sub: "COMING SOON",
    editorCopy: "Campaigns, soon.",
    dark: true,
    bg: "#1A1A1A",
    bgHover: "#1F1F1F",
  },
  {
    id: "myspace",
    num: "05",
    tab: "MY SPACE",
    sub: "COMING SOON",
    editorCopy: "Personalized curation, soon.",
    dark: true,
    bg: "#151515",
    bgHover: "#1A1A1A",
  },
];
