export const ANALYSIS_HISTORY = [
  { date: "Mar 8, 2026", wallet: "0x7a3b...9f2c", persona: "Strategic Holder" },
  { date: "Mar 5, 2026", wallet: "0x1D4e...a8B3", persona: "Profit Hunter" },
  { date: "Feb 28, 2026", wallet: "0xF92c...3e7A", persona: "Chain Hopper" },
  { date: "Feb 20, 2026", wallet: "0x8B1d...4c2F", persona: "NFT Collector" },
  { date: "Feb 15, 2026", wallet: "0xA3e7...d91B", persona: "Active Trader" },
  { date: "Feb 10, 2026", wallet: "0xC5f8...72eD", persona: "Cash Manager" },
  { date: "Feb 3, 2026", wallet: "0x2E9a...b4C1", persona: "Rising Star" },
  { date: "Jan 28, 2026", wallet: "0xD7b3...f8A2", persona: "Swing Trader" },
  { date: "Jan 20, 2026", wallet: "0x4F1c...e3D9", persona: "Major Investor" },
  { date: "Jan 15, 2026", wallet: "0x6A8d...1bF7", persona: "Community Leader" },
  { date: "Jan 8, 2026", wallet: "0x9C2e...5dA4", persona: "Smart Saver" },
  { date: "Dec 30, 2025", wallet: "0xB1f7...8cE3", persona: "Wealth Guard" },
];

export function getLookUpMock(wallet: string) {
  return {
    wallet,
    persona: "Strategic Holder",
    trends: [
      { label: "7D TREND", value: "+3.2%", up: true },
      { label: "30D TREND", value: "+12.4%", up: true },
      { label: "90D TREND", value: "-2.8%", up: false },
    ] as const,
    health: [
      { label: "Diversification", value: "High", tone: "green" as const },
      { label: "Chain Spread", value: "4 active", tone: "green" as const },
      { label: "Stable Ratio", value: "45%", tone: "green" as const },
      { label: "DeFi Usage", value: "Strong", tone: "green" as const },
    ] as const,
    also: ["Profit Hunter", "Chain Hopper"],
    tier: "Platinum",
    since: "Oct 2023",
    risk: "LOW",
    sybil: "CLEAN",
    flags: "NONE",
    entropy: "0.15",
    totalValue: "$142,300",
    txCount: "1,247",
    monthlyVol: "$12,010",
    activeChains: "4",
    defiTvl: "$68,200",
    nftCount: "12",
    unclaimed: "$4,120",
    assets: {
      stables: {
        pct: 45,
        total: "$64,000",
        tokens: [
          { name: "USDC", total: "$48,500", breakdown: [{ chain: "ETH", val: "$28,000" }, { chain: "BSC", val: "$12,000" }, { chain: "Base", val: "$5,200" }, { chain: "ARB", val: "$3,300" }] },
          { name: "USDT", total: "$11,500", breakdown: [{ chain: "ETH", val: "$8,800" }, { chain: "BSC", val: "$2,700" }] },
          { name: "BUSD", total: "$4,200", breakdown: [{ chain: "BSC", val: "$4,200" }] },
          { name: "DAI", total: "$2,100", breakdown: [{ chain: "ETH", val: "$2,100" }] },
          { name: "USDbC", total: "$1,200", breakdown: [{ chain: "Base", val: "$1,200" }] },
          { name: "Others", total: "$500", isOthers: true, breakdown: [{ chain: "Various", val: "$500" }] },
        ],
      },
      native: {
        pct: 35,
        total: "$49,800",
        tokens: [
          { name: "ETH", total: "$43,000", breakdown: [{ chain: "ETH", val: "$38,100" }, { chain: "Base", val: "$3,800" }, { chain: "ARB", val: "$1,100" }] },
          { name: "BNB", total: "$8,400", breakdown: [{ chain: "BSC", val: "$8,400" }] },
          { name: "MATIC", total: "$1,800", breakdown: [{ chain: "Polygon", val: "$1,800" }] },
          { name: "AVAX", total: "$1,200", breakdown: [{ chain: "Avalanche", val: "$1,200" }] },
          { name: "SOL", total: "$800", breakdown: [{ chain: "Solana", val: "$800" }] },
          { name: "Others", total: "$600", isOthers: true, breakdown: [{ chain: "Various", val: "$600" }] },
        ],
      },
      others: {
        pct: 20,
        total: "$28,500",
        tokens: [
          { name: "ARB", total: "$4,200", breakdown: [{ chain: "Arbitrum", val: "$4,200" }] },
          { name: "CAKE", total: "$3,100", breakdown: [{ chain: "BSC", val: "$3,100" }] },
          { name: "LINK", total: "$1,200", breakdown: [{ chain: "ETH", val: "$1,200" }] },
          { name: "AERO", total: "$980", breakdown: [{ chain: "Base", val: "$980" }] },
          { name: "cbETH", total: "$720", breakdown: [{ chain: "Base", val: "$720" }] },
          { name: "Others", total: "$18,300", isOthers: true, breakdown: [{ chain: "Various", val: "$18,300" }] },
        ],
      },
    },
    chains: [
      { name: "Ethereum", pct: 52, value: "$74,200", tokenCount: 5 },
      { name: "BSC", pct: 28, value: "$38,400", tokenCount: 5 },
      { name: "Base", pct: 12, value: "$17,100", tokenCount: 5 },
      { name: "Arbitrum", pct: 6, value: "$8,300", tokenCount: 4 },
      { name: "Others", pct: 2, value: "$4,300", tokenCount: 4 },
    ],
    funding: { cex: 55, bridge: 30, wallet: 15, top3: ["Binance", "OKX", "Bybit"] },
    defi: {
      lp: { pct: 40, protocols: [{ name: "Uniswap V3", pct: 45 }, { name: "Aerodrome", pct: 30 }, { name: "PancakeSwap", pct: 15 }, { name: "Others", pct: 10 }] },
      lending: { pct: 25, protocols: [{ name: "Aave V3", pct: 52 }, { name: "Compound", pct: 28 }, { name: "Venus", pct: 12 }, { name: "Others", pct: 8 }] },
      staking: { pct: 20, protocols: [{ name: "Lido", pct: 60 }, { name: "Rocket Pool", pct: 22 }, { name: "Eigenlayer", pct: 12 }, { name: "Others", pct: 6 }] },
      vault: { pct: 15, protocols: [{ name: "Yearn", pct: 48 }, { name: "Beefy", pct: 32 }, { name: "Convex", pct: 14 }, { name: "Others", pct: 6 }] },
    },
    transfer: { incoming: 68, outgoing: 32, inVal: "$96,800", outVal: "$45,500", top3: ["0xABCD...1234", "0x7F2E...89ab", "0x3D1C...ef56"] },
    gas: { total: "$2,340", top3Chains: ["Ethereum 72%", "BSC 18%", "Base 10%"], avgTx: "$1.87" },
    recentTx: [
      { date: "Mar 7", action: "Swap 2.5 ETH → USDC", platform: "Uniswap", chain: "Ethereum" },
      { date: "Mar 5", action: "Stake 1,000 USDC", platform: "Aave", chain: "Ethereum" },
      { date: "Mar 3", action: "Bridge 500 USDC", platform: "Across", chain: "ETH → Base" },
      { date: "Mar 1", action: "LP 2,000 USDC-ETH", platform: "Aerodrome", chain: "Base" },
      { date: "Feb 28", action: "Claim 45 ARB rewards", platform: "Arbitrum", chain: "Arbitrum" },
    ],
  };
}
